#!/bin/bash

dirkey="/etc/adm-server/keys"
[[ ! -e /etc/adm-server/credit ]] && echo "OFICIAL ADM-SERVER-IFS" > /etc/adm-server/credit
[[ ! -d $dirkey ]] && mkdir $dirkey

atualiza_fun () {
cd $HOME
wget https://www.dropbox.com/s/qo5gt4hsafiryrr/instala_server.sh -o /dev/null
chmod 777 ./instala_server
./instala_server
}

ofuscate_fun () {
number=$(expr length $1)
for((i=1; i<$(($number+1)); i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
if [ "${txt[$i]}" = "." ]; then
txt[$i]="#"
elif [ "${txt[$i]}" = "#" ]; then
txt[$i]="."
fi
if [ "${txt[$i]}" = "1" ]; then
txt[$i]="@"
elif [ "${txt[$i]}" = "@" ]; then
txt[$i]="1"
fi
if [ "${txt[$i]}" = "2" ]; then
txt[$i]="?"
elif [ "${txt[$i]}" = "?" ]; then
txt[$i]="2"
fi
if [ "${txt[$i]}" = "3" ]; then
txt[$i]="&"
elif [ "${txt[$i]}" = "&" ]; then
txt[$i]="3"
fi
txtofus+="${txt[$i]}"
done
obfus=$(echo $txtofus | rev)
txt_ofuscatw=$(echo $txtofus | rev)
unset varq
}

meu_ip () {
MIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MIP2=$(wget -qO- ipv4.icanhazip.com)
[[ "$MIP" != "$MIP2" ]] && IP="$MIP2" || IP="$MIP"
}

unset theserver
theserver=$(netstat -nltp|grep faucet)
[[ $theserver = "" ]] && theserver="\033[1;31m Fuera de linea" || theserver="\033[1;32m En linea"

amarelo="\033[1;33m"
verde="\033[1;32m"
vermelho="\033[1;31m"
branco="\033[1;37m"

clear
echo -e "\033[1;36m========================================\033[0;m"
echo -e "\033[4;32mADM GENERADOR IFS PLUS\033[0;m"
echo -e "\033[1;33m========================================\033[0;m"
echo -e "${vermelho}|1| - \033[1;37mCrear llave"
echo -e "\033[1;33m========================================\033[0;m"
echo -e "${vermelho}|2| - \033[1;37mEstadistica de Llaves"
echo -e "\033[1;33m========================================\033[0;m"
echo -e "${vermelho}|3| - \033[1;37mEliminar Llaves"
echo -e "\033[1;33m========================================\033[0;m"
echo -ne "${vermelho}|4| - \033[1;37miniciar/Detener sistema"; echo -e " (${theserver} ${amarelo})"
echo -e "\033[1;33m========================================\033[0;m"
echo -e "${vermelho}|5| - \033[1;37mActualizar Creditos!"
echo -e "\033[1;33m========================================\033[0;m"
echo -e "${vermelho}|6| - \033[1;31mComprobar atualizaciones!"
echo -e "\033[1;36m========================================\033[0;m"
echo -ne "Opciones: "; read options
meu_ip
ofuscate_fun "${IP}:81"
case $options in
1)
echo -ne "\033[1;37mNombre de la nueva llave (nombre/name)\033[0;m:${vermelho} "; read name
echo -ne "\033[1;37mCantidad de llaves a generar:\033[0;m (number):${vermelho} "; read num
echo -e "\033[1;33mGENERANDO... Espere\033[0;m"
for((k=0; k<$num; k++)); do
arch="$((100*$RANDOM*$RANDOM+$RANDOM))"
echo "$name" > ${dirkey}/${arch}
echo "${obfus}+${arch}"
done
echo -e "\033[1;37mGENERADA/S...\033[0;m'"
;;
2)
numkey="$(ls ${dirkey}|wc -l)"
echo -ne "\033[1;37mNumero de Llaves Activas:\033[0;m "; echo -e "${vermelho}$numkey"
[[ ${numkey} = "0" ]] && exit
for keys in $(ls ${dirkey}); do
unset dono
dono=$(cat ${dirkey}/${keys}|head -1)
key+="$dono|${obfus}+${keys}\n"
done
for i in $(echo -e ${key}|sort); do
usuario=$(echo -e "$i"|cut -d'|' -f1)
keys=$(echo -e "$i"|cut -d'|' -f2)
echo -e "\033[1;33mUsuario: ${vermelho}$usuario \033[1;33mKey Ativas:${vermelho} $keys"
done
;;
3)
i=0
echo -ne "${amarelo}"
for arqs in $(ls ${dirkey}); do
rm[$i]="$arqs"
echo -e "[$i] - ${obfus}+${arqs}"
i=$(($i+1))
done
echo -ne "\033[1;31mEscoja la llave que va a ser eliminada: ${branco}"; read remo
if [[ $remo = "" ]]; then
echo ""
elif [[ $remo -gt "$(($i-1))" ]]; then
echo ""
else
[[ ! -e "${dirkey}/${rm[$remo]}" ]] && exit || rm ${dirkey}/${rm[$remo]}
fi
;;
4)
if [[ $(netstat -nltp|grep faucet) = "" ]]; then
keyserver.sh -start "/bin/keyserver.sh"
else
killall faucet
fi
;;
5)
echo -ne "\033[1;37mNuevo credito para ADM:\033[0;m ${branco}"; read newcredit
echo "$newcredit" > /etc/adm-server/credit
;;
6)
atualiza_fun
;;
esac
echo -ne "\033[0m"
exit